Endpointy zwracające sklepy na podstawie dystansu działają
taylor-swif/Krakoskie-Obwarzanki pull request #29
Opened 2024-05-30 23:15 UTC by stylub

### !!! struktura `Shop` została zmieniona !!!
* * * 
* Funckja licząca odległość między punktami została zastąpiona poprzez wbudowane funkcjonalności bazy danych (teraz dane są faktycznie ułożone na podstawie danych geolokacyjnych)
*  Endpointy zwracające sklepy na podstawie dystansu działają poprawnie i dodatkowo zwracają odległość - w strukturze `Shop` nowe pole `distance` które jest Optional
* z powodu zmiany struktury `Shop` stare dane przestały być poprawne oraz frontend teraz oczekuje danych w złym formacie

2024-05-31 06:36 UTC, ReptilianEye commented on backend/app/server/models/shop.py
> +    coordinates: List[float]
Żeby było super ładnie zrobiłbym taki alias na typ:
python```
type Coordinates = tuple[float,float] 
```
albo List jak trzeba, aby było jeszcze bardziej czytelne

2024-05-31 06:38 UTC, ReptilianEye commented on backend/app/server/models/shop.py
> +        collection = "shops"
Dlaczego tutaj zmieniłeś na `collection`? `name` było potrzebne Beanie do nazwania collection

2024-05-31 06:49 UTC, ReptilianEye commented on backend/app/server/app.py
> +    return [shop.dict() for shop in shops]
Nie musisz tutaj zmieniać na nowo na słownik. Jak zwrócisz shops to będzie działać

2024-05-31 06:49 UTC, ReptilianEye commented on backend/app/server/app.py
> +    return [shop.dict() for shop in shops]
To co wyżej

2024-05-31 06:52 UTC, ReptilianEye commented on backend/app/server/app.py
> +from bson.son import SON
chyba do usunięcia

2024-05-31 06:52 UTC, ReptilianEye commented on backend/app/server/models/shop.py
> +from beanie import Document, PydanticObjectId
To ja zostawiłem ale można usunąć nieużywane importy

2024-05-31 06:55 UTC, ReptilianEye commented on backend/app/server/database.py
> +    await shop_collection.create_index([("location", "2dsphere")])
index dodawaj w klasie Shop (możesz całą kolejke usunąć w razie czego), tak jak w tym tutorialu https://dev.to/romanright/mongodb-indexes-with-beanie-43e8

2024-05-31 06:58 UTC, ReptilianEye commented on backend/app/server/models/shop.py
> +    distance: Optional[float]
Ten distance jest potrzebny do tej agregacji z najbliższymi sklepami? Zapisujemy ją w bazie danych?

2024-05-31 07:28 UTC, ReptilianEye commented on backend/app/server/models/shop.py
> +    coordinates: List[float]
Jest jeszcze jeden problem. Jak zwracamy taki model z tym `Point` to json ma taki fragment:
`    "location": {
      "type": "Point",
      "coordinates": [
        51.1867762716661,
        20.01512298583985
      ]
    },
`
i to jest takie średnie aby to parsować na froncie. Ja też poszukam, ale super byłoby jakby sie dało to zwracać najlepiej bez tego typu.

2024-05-31 07:29 UTC, ReptilianEye requested changes
Tak jak w komentarzach.

2024-05-31 23:13 UTC, stylub commented on backend/app/server/app.py
> +    return [shop.dict() for shop in shops]
Takie coś można zrobić żeby na froncie można było łatwiej parsować. Możesz ocenić co myślisz o takim rozwiązaniu.

2024-05-31 23:14 UTC, stylub commented
Dodałem większość proponowanych zmian i dokonałem lekkiej refaktoryzacji.

2024-06-01 05:50 UTC, ReptilianEye commented
Tak mniej więcej chyba bym to widział jak w tym commicie [a326a85](https://github.com/taylor-swif/Krakoskie-Obwarzanki/pull/29/commits/a326a85deae468b27b5c57d274c23b5d0bdb9437)
Co myślisz?

2024-06-01 07:09 UTC, ReptilianEye commented
Poprawiłem jeszcze frontend, teraz powinno wszędzie działać

2024-06-01 08:17 UTC, ReptilianEye approved these changes
Myśle że teraz już będzie git

2024-06-01 10:22 UTC, ReptilianEye approved these changes
Gites jest

2024-06-01 10:27 UTC, merged